### PR TITLE
Mood Based Music Recommender

### PR DESCRIPTION
**Pull request by Haob2110011**
### Developer Checklist
- [ ] Adhered to the guidelines outlined in the README & Contributing file.
- [ ] Maintained the correct directory structure (e.g., ProjectName/...yourfiles).
- [ ] Please ensure to include a README file for enhanced project clarity.
- [ ] Starred ⭐ the repository (optional).

### Summary
Hello sir, sorry for the mistake, i didn't know i need to create a pull request for you to merge. please check for me, thank you

### CODE REVIEW

**Comment by king04aman** [comment]
Can you please remove issue number #30 from your project directory name ?

**Comment by Haob2110011** [comment]
@king04aman, I have already done, rename tittle of this issue and the directory name to "Mood Based Music Recommender". I committed again. Check it out if you have some free time!
Have a nice day!!

**Comment by Haob2110011** [comment]
Hi Aman Kumar! Please help me check it! I'm waiting for you!

**Comment by Haob2110011** [comment]
Hi @king04aman ,
I hope this message finds you well. I wanted to kindly ask if you could review and merge my pull request into the branch when you have a moment.
Please let me know if you need any additional information or if there’s anything I can assist with to help the process along. I really appreciate your time and support!

**Review by king04aman — APPROVED** [review]

**Comment by Haob2110011** [comment]
Thank you for supporting me. Best regard!!

**Pull request merged**
