### PR TITLE
Contribution to Issue #14 - Added python script for expense splitter

### PR DESCRIPTION
**Pull request by rkt-1597**
@king04aman This PR implenents an expense splitter python script.

### CODE REVIEW

**Comment by king04aman** [comment]
Thank you for your contribution! The expense splitter script is a solid start, and I appreciate your effort. To enhance it further, consider adding docstrings to your functions for clarity, implementing input validation to ensure users enter valid amounts, and making the confirmation input case-insensitive for a better user experience. Additionally, please follow the contributing guidelines by including a `requirements.txt` file for dependencies and a `README.md` to explain how to use the script, along with a `runtime` file to specify the Python version. These changes will improve the maintainability of your code.

**Comment by rkt-1597** [comment]
Yes

**Comment by rkt-1597** [comment]
@king04aman , the requirements.txt file would be empty in this case, as there is no particular python library used in this script, right?

**Comment by king04aman** [comment]
The script lacks input validation, potentially causing errors if users enter non-integer values or invalid inputs. Variable names such as chk1, n, a, num, and amt are unclear and should be renamed for better understanding (e.g., add_members, member_name, contribution, total_members, and contributions) also consider adding `**README.md**` file

**Pull request closed without merging**
