### PR TITLE
 Initial YouTube Video Downloader project with yt-dlp integration

### PR DESCRIPTION
**Pull request by nepal143**
This pull request introduces the initial implementation of the YouTube Video Downloader project, featuring the integration of the `yt-dlp` library for downloading YouTube videos.

Key Features:
- Ability to download videos in the highest available resolution or a user-specified resolution (e.g., 720p).
- Simple input prompts for YouTube URL and resolution.
- Error handling for invalid URLs or resolution mismatches.
- Includes configuration files:
  - `requirements.txt` for project dependencies (`yt-dlp`).
  - `runtime.txt` specifying the Python version (Python 3.10.12).
  
This setup ensures a smooth installation of dependencies and correct runtime environment for the project.

Please review and suggest any necessary changes or improvements. 
#2

### CODE REVIEW

**Comment by king04aman** [comment]
Great job on implementing the YouTube Video Downloader project. Adding a README will significantly improve the project's accessibility and clarity.

**Comment by nepal143** [comment]
Hi @king04aman ,

I've added the README as requested to improve the project's documentation. Let me know if anything else is needed!

**Review by king04aman — CHANGES_REQUESTED** [review]
As **Recipe Finder with Meal Planner** is already merged. Can you please separate them from this PR? It would be create to create separate PR for each of them.

**Comment by nepal143** [comment]
I had done the  required changes please review

**Pull request merged**
