### PR TITLE
Adds weather Alert notification system

### PR DESCRIPTION
**Pull request by Telomelonia**
solves #15 
Adds the weather alert notification py script

I used `https://api.openweathermap.org/data/2.5/find`

### CODE REVIEW

**Comment by Telomelonia** [comment]
@king04aman plz review this

**Comment by king04aman** [comment]
Thank you for your contribution! I really appreciate your work on the weather alert notification system—as it's a great start. I have a few suggestions that could help enhance it even further:

1. Security - Please use environment variables to store the API key instead of hard-coding it.
2. Error Handling - Enhance error handling by catching specific exceptions to better identify issues.
3. Input Validation - Add validation for user inputs to ensure they are numeric and sensible.
4. Function Documentation - Include docstrings for your functions to improve clarity.
5. Logging - Consider using a logging framework instead of print statements for better output management.

These tweaks would make the code more secure and easier to maintain. I’m excited to see your updates!

**Comment by Telomelonia** [comment]
@king04aman 
made the required changes

**Comment by Telomelonia** [comment]
> Adding a README file significantly increase project clarity and understanding.
Done 👍

**Review by king04aman — APPROVED** [review]

**Pull request merged**
