### PR TITLE
a CLI interactive Python based Resume Builder

### PR DESCRIPTION
**Pull request by akshatgithubgre**
### Developer Checklist
- [ ] Adhered to the guidelines outlined in the README & Contributing file.
- [ ] Maintained the correct directory structure (e.g., ProjectName/...yourfiles).
- [ ] Please ensure to include a README file for enhanced project clarity.
- [ ] Starred ⭐ the repository (optional).
#51

### CODE REVIEW

**Comment by saurabh-23232** [comment]
@akshatgithubgre how you going to fix "all checks have failed" let me know this as well. I'm facing the same issue

**Comment by akshatgithubgre** [comment]
well i didnt get why these checks have not passd, please can someone tell me

**Comment by king04aman** [comment]
Hi @akshatgithubgre  and @saurabh-23232,

Thanks for your feedback! I’ve fixed the issues, and all checks should now pass. I’ll review your code and merge it ASAP.

**Review by king04aman — CHANGES_REQUESTED** [review]
- Provided project overview, features, setup instructions, usage details, dependencies, and license information.
- Included necessary dependencies and their version (geopy, prompt_toolkit, fpdf).
- Developed main functionalities for adding resume sections, generating the PDF, and creating an interactive menu.
Overall, project enhances the resume-building experience through an intuitive CLI interface.

**Review by akshatgithubgre — COMMENTED** [review]
made the required changes 
please can you check mnd merge this PR

**Comment by akshatgithubgre** [comment]
hey please can you review the chanegs and merge this PR

**Review by king04aman — APPROVED** [review]

**Pull request merged**
