### PR TITLE
Python script to calculate GPA for any semester or overall in college

### PR DESCRIPTION
**Pull request by gundeep77**
### Developer Checklist
- [ ] Adhered to the guidelines outlined in the README & Contributing file.
- [ ] Maintained the correct directory structure (e.g., ProjectName/...yourfiles).
- [ ] Please ensure to include a README file for enhanced project clarity.
- [ ] Starred ⭐ the repository (optional).

### CODE REVIEW

**Review by king04aman — CHANGES_REQUESTED** [review]
- Add input sanitization and more robust error handling
- Implement unit tests to validate GPA calculations for different scenarios.
- Create a requirements.txt and README.md for usability and setup.

**Comment by king04aman** [comment]
Hi @gundeep77 ,

I wanted to check in regarding the feedback provided in the last review. Do you have any updates on the changes? I’m looking forward to your progress!

**Comment by gundeep77** [comment]
> Hi @gundeep77 ,
> 
> I wanted to check in regarding the feedback provided in the last review. Do you have any updates on the changes? I’m looking forward to your progress!

Hey Aman,

I am really sorry man!
Got too busy with work. I wont be continuing this.
You can reject my PR

Sorry once again!

**Comment by king04aman** [comment]
It's okay @gundeep77 , thanks for the update.

**Pull request closed without merging**
